ENVIRONMENT:
  MAX_EPISODE_STEPS: 2500
SIMULATOR:
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  ACTION_SPACE_CONFIG: "v1"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    # HEIGHT: 0.8
    # RADIUS: 0.1
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
  SEMANTIC_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 79
    POSITION: [0, 0.88, 0]
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 79
    POSITION: [0, 0.88, 0]
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 79
    MIN_DEPTH: 0.5
    MAX_DEPTH: 5.0
    POSITION: [0, 0.88, 0]
TASK:
  TYPE: MultiNav-v1
  COMMUNICATION: structured
  # POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "LOOK_UP", "LOOK_DOWN", "FOUND"]
  POSSIBLE_ACTIONS: ["FOUND", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]

  SUCCESS_DISTANCE: 1.5

  # SENSORS: ['MULTI_GOAL_SENSOR', "POSITION_SENSOR", "HEADING_SENSOR", "MAP_SENSOR"]
  SENSORS: ['MULTI_GOAL_SENSOR', "POSITION_SENSOR", "HEADING_SENSOR"]



  GOAL_SENSOR_UUID: multiobjectgoal

  # MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'WPL']
  # MEASUREMENTS: ['RATIO', 'DISTANCE_TO_CURR_GOAL', 'DISTANCE_TO_MULTI_GOAL', 'SUB_SUCCESS', 'SUCCESS', 'EPISODE_LENGTH', 'MSPL', 'PERCENTAGE_SUCCESS', 'SEEN_MAP', 'PSPL', 'RAW_METRICS', 'TRAJ_METRICS']
  MEASUREMENTS: ['RATIO', 'DISTANCE_TO_CURR_GOAL', 'DISTANCE_TO_MULTI_GOAL', 'SUB_SUCCESS', 'SUCCESS', 'EPISODE_LENGTH', 'MSPL', 'PERCENTAGE_SUCCESS', 'PSPL', 'RAW_METRICS',  'TOP_DOWN_MAP']

  SUCCESS:
    SUCCESS_DISTANCE: 1.5
  DISTANCE_TO_GOAL:
    DISTANCE_TO: POINT

DATASET:
  TYPE: MultiNav-v1
  SPLIT: train
  DATA_PATH: "data/datasets/multinav/9000Ep_2G_GdvgFV5R1Z5/v1/{split}/{split}.json.gz"
  SCENES_DIR: "data/scene_datasets/"
